version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: digit-opus-hub-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: digit_opus_hub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - digit-opus-network

  # Redis 缓存和队列
  redis:
    image: redis:7-alpine
    container_name: digit-opus-hub-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - digit-opus-network

  # 后端 API（开发模式）
  server:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    container_name: digit-opus-hub-server
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres:5432/digit_opus_hub?schema=public
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-dev-secret-key-change-in-production}
      JWT_EXPIRES_IN: 7d
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      PORT: 3000
      FRONTEND_URL: http://localhost:5173
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./server:/app
      - ./prisma:/app/prisma
      - /app/node_modules
      - /app/dist
    networks:
      - digit-opus-network
    restart: unless-stopped

  # 前端应用（开发模式）
  client:
    build:
      context: .
      dockerfile: client/Dockerfile.dev
    container_name: digit-opus-hub-client
    environment:
      VITE_API_URL: http://localhost:3000/api
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - digit-opus-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  digit-opus-network:
    driver: bridge
